export const constants = {
    api_url: 'http://sandbox.voolsy.in/',
    headers: {'Content-Type': 'application/json','Access-Control-Allow-Origin' :'*'},
    banner_params : {
        'device_type': 'web', 
        'custom_app_id': '', 
        'device_platform': '', 
        'device_id': '', 
        'app_version': 100, 
        'app_version_code': 100, 
        'is_test_live': 0, 
        'is_prepayment_applicable': 1, 
        'is_cash_and_carry_applicable': 0, 
        'is_token_order': 0, 
        'user_id': 0, 
        'current_latitude': 0.000000, 
        'current_longitude': 0.000000, 
        'restaurant_id': 2, 
        'branch_id': 4, 
        'WS_USER_URL': 'http://sandbox.voolsy.in/userswebservicesv6/', 
        'verify_token': 0, 
        'voolsy_white_label_key': '', 
        'email_address': '', 
        'g-token': '03AFcWeA6kbxc917OQsiHlmV2jMSdP_P8XPWfyYGGmWwmUqD7dQu6s74b0SfxrMCAzf3sxNXCvuMvGf8-LuUVsxON_IdQVL7GmhyaCwbE79qmB33tteCkxiNRnGLaiKCa6CAxFTxPuZs6qajSOs-MMwnWxcrqjScfodp03kSKNzqN4wDRTwY7ZV0iHDBp0DDC0rCex72BYClFzSoxSPc-hOB5OP8UsVXAE1fB5hy7rr3sUsQ9gcccKa6bYnW65v8I8jkjNg9gH_O5oOQkVkbycWXWRC2PueIbGp5aaCAmwnVFc9UzZBFEpP_FB8HrEYlSlSEo-h_ExIVR0G9EqiKCft1odMdkukNi5zhbv3If5u1Rbxyxl0-I7SBP1a2qjp1Ip-6GCujxywjwY6eHrZvQOn9efq19jbcWTsndtaGpXL1nw_0C42o5vR8EnnYUTtODQTL202jZt2LVDe_5XxVFfjkxYF_g47k1xIvRKTzkbz2aeEuVdRLlrsFT3nOBd19f30QLLVlmMnyCexQMDqNmCJmw8vP737Bre-_G575QlU0kQv4jdu2LeIyGAZctTd3Mnw-UZCyQZm6jWJz9bqpmF5ksxxOLddxVHay27uQ-aRTMTHg-Wssb9JdKatbXKy8gOC0Rjm1OaV24y7F-3mX1sMaeF-aLmN9ttRLb-Z4h0ydax9Jn9-xh1t3E', 
      }
  };